// AUTO-GENERATED by scripts/gen-keys.mjs — do not edit by hand.
//
// The ed25519 public key that verifies content-update manifests. This is the
// static trust root of the updater: the shell trusts ONLY bundles whose manifest
// is signed by the matching private key (kept out of the repo, used at release
// time). Rotating it requires shipping a new shell build.
export const CONTENT_PUBLIC_KEY_PEM =
  '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEALhkXP1SMRSl2l+BCJAsKiSPoBlxBU/Cy40myH2HJXCU=\n-----END PUBLIC KEY-----\n';
