// Generates the ed25519 signing keypair used to sign content-update manifests.
//
//   node scripts/gen-keys.mjs
//
// Writes:
//   keys/content-private-key.pem        -> the RELEASE SECRET (gitignored, never commit)
//   src/shell/content-public-key.ts     -> bundled into the shell, verifies updates
//
// The private key signs `manifest.json` at release time (scripts/pack-content.mjs).
// The public key is compiled into the Electron shell and used to verify every
// downloaded manifest before any bundle is trusted. Rotating keys is a SHELL
// change (re-ship the app), by design — the trust root must stay static.
//
// Re-running OVERWRITES both files. Do this only when intentionally rotating the
// key; existing published manifests signed with the old key will stop verifying.
import { generateKeyPairSync } from 'node:crypto';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const privPath = path.join(pkgDir, 'keys', 'content-private-key.pem');
const pubTsPath = path.join(pkgDir, 'src', 'shell', 'content-public-key.ts');

if (existsSync(privPath) && !process.argv.includes('--force')) {
  console.error(
    `Refusing to overwrite existing private key at:\n  ${privPath}\n` +
      `Re-run with --force ONLY if you intend to rotate the signing key (this ` +
      `invalidates all previously published manifests).`,
  );
  process.exit(1);
}

const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const privPem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const pubPem = publicKey.export({ type: 'spki', format: 'pem' });

mkdirSync(path.dirname(privPath), { recursive: true });
writeFileSync(privPath, privPem);

const ts = `// AUTO-GENERATED by scripts/gen-keys.mjs — do not edit by hand.
//
// The ed25519 public key that verifies content-update manifests. This is the
// static trust root of the updater: the shell trusts ONLY bundles whose manifest
// is signed by the matching private key (kept out of the repo, used at release
// time). Rotating it requires shipping a new shell build.
export const CONTENT_PUBLIC_KEY_PEM = ${JSON.stringify(pubPem)};
`;
writeFileSync(pubTsPath, ts);

console.log('Wrote private key  ->', privPath, '(gitignored — keep secret)');
console.log('Wrote public key   ->', pubTsPath, '(bundled into the shell)');
